### ISSUE TITLE
Open Local Gemini Files

### ISSUE THREAD

**Issue by Daveed9** [makeworld-the-better-one/amfora#103]
Opening a `.gmi` or `.gemini` file that is stored locally does not seem to be implemented. It would be a nice feature to be able to view a document as you write it.

**Comment by makeworld-the-better-one** [comment]
I agree! I think to keep things simple, I would only like to handle files that end in `.gmi`, `.gemini` and `.txt`, as we don't have access to MIME type information like we do over Gemini. The scheme would be `file://` like it is for regular browsers, and there would have to be a simple folder view as well, that would maybe only show the files it could open, and subfolders.

I would accept a PR for this, or will get to it at some point.

**Comment by makeworld-the-better-one** [comment]
See #147 for some more about the `file://` URI.
