### ISSUE TITLE
Theme support for help page

### ISSUE THREAD

**Issue by lokesh-krishna** [makeworld-the-better-one/amfora#105]
Could you please add keys to set the background and foreground colors for the help page? The one that's brought up by pressing `?`.

**Comment by lokesh-krishna** [comment]
As a novice, if you're willing to point me in the right direction then I'd love to take this up.

**Comment by makeworld-the-better-one** [comment]
Actually, I believe #107 will fix this. Once that is merged, you will be able to set the help page background with the `bg` key. Do you need a separate key, or is that fine?

**Comment by makeworld-the-better-one** [comment]
Also, if you are creating custom themes I'd love for you to upload them for others to use. Up to you!

**Comment by lokesh-krishna** [comment]
Setting it with `bg` would be perfect. That's all I need :)  
Where can I share my custom theme? Is there a separate repository or a thread in this one?

**Comment by makeworld-the-better-one** [comment]
There's no other repo right now. How about you make a PR that adds the `[theme]` section of your config as a `.toml` file in a new `contrib/themes` folder? Excited to see it!
