### ISSUE TITLE
Select link > 10 with numbers

### ISSUE THREAD

**Issue by graphixillusion** [makeworld-the-better-one/amfora#108]
Hi there. As the title says, i didn't find a way to select a link with a greater number than 10. Pressing fast 1,1 for number 11 for example doesn't work. Actually the only way is to select it manually with enter-->tab. Thank you.

**Comment by makeworld-the-better-one** [comment]
You can also press the spacebar, and then type the link number. This is documented on the help page (press <kbd>?</kbd>):

```
 spacebar             Open bar at the bottom - type a URL, link number, search term.                                                              
                      You can also type two dots (..) to go up a directory in the URL.                                                                               
                      Typing new:N will open link number N in a new tab                                                                                     
                      instead of the current one.
```

Happy to hear you're using Amfora!

**Comment by graphixillusion** [comment]
@makeworld-the-better-one sorry, i've read the documentation but didn't notice that it works for link numbers too. thank you again for the support.
