### ISSUE TITLE
Add a cache time limit

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#110]
Currently all visited pages are cached until the session is over, unless the user pressed <kbd>Ctrl-R</kbd>. However it's not unlikely for a user to leave Amfora open for long periods of time. Maybe all cached pages should have a `CachedAt` time value and be removed from the cache after a period of time, maybe 30 minutes?

**Comment by sotpapathe** [comment]
This would be nice to have!

I had a look at the [HTTP/1.1 Caching RFC](https://tools.ietf.org/html/rfc7234) for some inspiration on the cache timeout. It only mentions [a heuristic given the last modified time](https://tools.ietf.org/html/rfc7234#section-4.2.2) which is not applicable to gemini.

30 minutes sound like a sensible choice. Having a keybinding (`Shift+R`) to force fetching the page before expiration is probably a good idea.

**Comment by makeworld-the-better-one** [comment]
<kbd>Shift-R</kbd> and <kbd>Ctrl-R</kbd> already do this, reloading the page and putting the new version in cache. They'd continue to work after this change is made.

**Comment by makeworld-the-better-one** [comment]
And yes, I feel that 30 mins is good too.
