### ISSUE TITLE
`bg` setting having no effect

### ISSUE THREAD

**Issue by uoou** [makeworld-the-better-one/amfora#119]
Hello. I'm having an issue with setting colours. The `bg` setting seems to do nothing. The config is being read as, as you can see in the screenshot, the `tab_divider` setting is taking.

I'm using the version in the Arch Linux repos:

```
Amfora 1.6.0
Commit: 445be96e467a959aff6dc8aaf75ca8751ce6f2d7
Built by: Arch_Linux
```

Apologies if this is my doing something incorrectly.

Edit: The problem seems to be specific to the `st` terminal. At least, it works correctly in Alacritty.

![2020-11-13_144407_906440301](https://user-images.githubusercontent.com/5243056/99084399-cd1a5100-25be-11eb-8e81-625de64d5962.jpg)

**Comment by makeworld-the-better-one** [comment]
Thanks for using Amfora!

`st` supposedly supports truecolor, but maybe the version you're using has issues with that? Look into various truecolor test commands, see [here](https://gist.github.com/XVilka/8346728) and the other links in that document.

Since this works fine in other terminals I will close this, but feel free to post an update here if you figure it out, so other people can find the solution too.

**Comment by uoou** [comment]
Thanks for the reply. Truecolor support seems fine (insomuch as the tests look right). I'll keep poking.

**Comment by makeworld-the-better-one** [comment]
Sounds like possibly an issue with [tcell](https://github.com/gdamore/tcell) then. Maybe check out if there have been any other issues in the past, or run an example tcell program to see if truecolor support works there. Maybe it works but tcell isn't detecting it properly. Note I am not using the latest version of tcell, but instead from commit `cb1e5d6fa606`.

**Comment by uoou** [comment]
Thanks, I appreciate the help. I'll have a look in that direction.

**Comment by uoou** [comment]
I was mistaken when I said that setting the `bg` value had no effect (the effect was just imperceptible whilst I was trying to make it dark).

Here's what it looks like when I try to set ff0000, 00ff00 and 0000ff respectively:
![2020-11-13_153136_156570841](https://user-images.githubusercontent.com/5243056/99089765-a01d6c80-25c5-11eb-9d14-8d237028b9bb.png)

The colours it's ending up with are from my 16 colour palette. So rather than using the (24-bit) colour specified it's going to the most appropriate match from my 16 colours.
