### ISSUE TITLE
amfora on Termux

### ISSUE THREAD

**Issue by lokesh-krishna** [makeworld-the-better-one/amfora#120]
Using the arm64 binary on Termux 0.101 (running on a Xiaomi Redmi Note 7 Pro on Android 10), I get the following error on attempting to access any Gemini site (the message below is when I attempted to visit cosmic.voyage):
```
Failed to connect to the server: dial tcp: lookup cosmic.voyage on [::1]:53: read udp [::1]:33263 -> [::1]:53
read connection refused.
```
Is this a limitation of Termux itself and if so, is it something that amfora can adapt to?

**Comment by makeworld-the-better-one** [comment]
This looks like a general termux issue, see [here](https://stackoverflow.com/questions/38959067/dns-lookup-issue-when-running-my-go-app-in-termux). You might need to have a rooted phone to use the accepted solution, but I would also look into what the [last one](https://stackoverflow.com/a/64600775/7361270) suggests, which is using `termux-chroot`.

Also it's cool to hear you're running Amfora on your phone! Would love to have an outside picture of your phone running it.

**Comment by lokesh-krishna** [comment]
Thanks for that link! `termux-chroot` works perfectly!

And here's the awesomeness that you made possible :)

![20201116_080324](https://user-images.githubusercontent.com/20235646/99207305-9ec98b00-27e3-11eb-9c22-a9dbc1e79b2c.jpg)

**Comment by makeworld-the-better-one** [comment]
Awesome :smile: 

Glad `termux-chroot` worked! Feel free to send steps here if it was anything more complicated than just running that command and then running `amfora`.
