### ISSUE TITLE
Can't use numpad enter in bottom bar

### ISSUE THREAD

**Issue by cole-h** [makeworld-the-better-one/amfora#123]
Hi!

I recently learned about gemini and amfora (like, within the past hour). Though I haven't been playing with it long, I'm digging it.

One issue I just ran into is the fact that I cannot use the enter key on my numpad, but only in the bottom bar (e.g. what appears when pressing the spacebar). It works fine in my terminal, and it even works fine on any ole page (after patching it with the below patch), but the bottom bar just does not want to respond to my numpad enter... Maybe there's something I overlooked (since I don't really use Go, and am unfamiliar with both this codebase and `tcell`).

```patch
commit b51cab07f704fa1b8dc8692483191166710dc7fe
Author: Cole Helbling <cole.e.helbling@outlook.com>
Date:   Wed Nov 18 23:18:05 2020 -0800

    display: support numpad enter
    
    tcell doesn't have a "nice" keycode for numpad enter, but in `showkey
    -a`, it shows as `^J`. I added `tcell.KeyCtrlJ` everywhere
    `tcell.KeyEnter` was referenced.

diff --git a/display/display.go b/display/display.go
index d2b6921..68222ab 100644
--- a/display/display.go
+++ b/display/display.go
@@ -115,7 +115,7 @@ func Init() {
 
 		//nolint:exhaustive
 		switch key {
-		case tcell.KeyEnter:
+		case tcell.KeyEnter, tcell.KeyCtrlJ:
 			// Figure out whether it's a URL, link number, or search
 			// And send out a request
 
diff --git a/display/help.go b/display/help.go
index 1391a07..87a4e3a 100644
--- a/display/help.go
+++ b/display/help.go
@@ -63,7 +63,7 @@ func Help() {
 func helpInit() {
 	// Populate help table
 	helpTable.SetDoneFunc(func(key tcell.Key) {
-		if key == tcell.KeyEsc || key == tcell.KeyEnter {
+		if key == tcell.KeyEsc || key == tcell.KeyEnter || key == tcell.KeyCtrlJ {
 			tabPages.SwitchToPage(strconv.Itoa(curTab))
 			App.SetFocus(tabs[curTab].view)
 			App.Draw()
diff --git a/display/tab.go b/display/tab.go
index f192720..9c52314 100644
--- a/display/tab.go
+++ b/display/tab.go
@@ -76,7 +76,7 @@ func makeNewTab() *tab {
 		currentSelection := tabs[tab].view.GetHighlights()
 		numSelections := len(tabs[tab].page.Links)
 
-		if key == tcell.KeyEnter && len(currentSelection) > 0 {
+		if (key == tcell.KeyEnter || key == tcell.KeyCtrlJ) && len(currentSelection) > 0 {
 			// A link is selected and enter was pressed: "click" it and load the page it's for
 			bottomBar.SetLabel("")
 			linkN, _ := strconv.Atoi(currentSelection[0])
@@ -85,7 +85,7 @@ func makeNewTab() *tab {
 			followLink(tabs[tab], tabs[tab].page.URL, tabs[tab].page.Links[linkN])
 			return
 		}
-		if len(currentSelection) == 0 && (key == tcell.KeyEnter || key == tcell.KeyTab) {
+		if len(currentSelection) == 0 && (key == tcell.KeyEnter || key == tcell.KeyCtrlJ || key == tcell.KeyTab) {
 			// They've started link highlighting
 			tabs[tab].page.Mode = structs.ModeLinkSelect
 
```

**Comment by makeworld-the-better-one** [comment]
> I recently learned about gemini and amfora (like, within the past hour). Though I haven't been playing with it long, I'm digging it.

Happy to hear it! Gemini is a great place.

As for your issue, [Wikipedia](https://en.wikipedia.org/wiki/Enter_key) informs me that the numpad enter is the Enter key, while the normal one is actually the Return key. It appears tcell does not support the Enter key properly, I will file a bug.

If you're interested, in seems that Ctrl-J is equivalent to ASCII key code 10 (as `showkey -a` will tell you), which is a Line Feed, or `\n`. [Source](https://www.codetable.net/asciikeycodes). So the numpad enter is returning `\n`, while the Return key is returning `\r`.

I've fixed this in 4b78a13, thanks for the patch! I changed things slightly.

**Comment by cole-h** [comment]
Great, thanks! One minor issue that remains is: `KeyCtrlJ` does not appear to work in the `spacebar` menu (`URL/Num./Search`). It works everywhere else, so I don't know what could be happening. Would you like me to open a new issue for this?

**Comment by makeworld-the-better-one** [comment]
That element is from [cview](https://gitlab.com/tslocum/cview/) and is out of my hands. If you look at the documentation for `InputField.SetDoneFunc` you'll see it triggers on `tcell.KeyEnter` and others, but not anything that works for you.

Furthermore, I've been [informed](https://github.com/gdamore/tcell/issues/411#issuecomment-731653560) that a line feed being returned is not a standard. It's often used on Unix systems but not guaranteed, and is different on Windows systems. I'm thinking I might undo this, since it can't reliably be detected, or even used, like with the bottom bar as you found. I'd rather not support it than partially support it.

**Comment by cole-h** [comment]
I see. Yeah, feel free to undo. I can solve this by binding `KeypadEnter` to send `0xd` (`^M`, same as enter key) in my Alacritty config.

**Comment by makeworld-the-better-one** [comment]
Oh! Okay perfect. Will undo.

**Comment by cole-h** [comment]
Sorry about that. But I do appreciate the fast turnaround!

Looking forward to doing more diving into Gemini with this.
