### ISSUE TITLE
Improving link navigation using the keyboard

### ISSUE THREAD

**Issue by lokesh-krishna** [makeworld-the-better-one/amfora#128]
Presently, it's only possible to access the first 9 links in a page using the number shortcuts. Would you be willing to consider a system where you can enter a number corresponding to a link on the page but then need to suffix it with a character in order to follow that link?  

So if there are more than 9 links in a page and the user wants to visit the 23rd link then they would enter `23G`.  

I feel like this would vastly improve the user experience, especially on aggregator pages where there might be upwards of 30 links on screen at once. 

The present system of tabbing through links doesn't lend itself all that well to paging through such a list either if you're using `j` or`k` because then entering tab would make it return to the last link that had been highlighted. With the proposed system, you would just immediately enter the number followed by the suffix key and go to the link without having to tab your way back to wherever you were on the page first.

**Comment by makeworld-the-better-one** [comment]
Currently you can press the spacebar, type the link number, and then press enter. I feel like that's good enough for link navigation right now. Were you aware of this method? You wouldn't be the first to not know... something to add to the docs I guess.

**Comment by lokesh-krishna** [comment]
Oh, that is fantastic. I had no idea that's a thing though so mentioning it in the docs would be nice :)
