### ISSUE TITLE
Option to open with proxy or url-handler

### ISSUE THREAD

**Issue by lokesh-krishna** [makeworld-the-better-one/amfora#143]
I usually face this problem when I come across HTTP links. I have a HTTP proxy setup but due the nature of HTTP, this is only truly function for minimal, text-focused pages. I would prefer launching my browser, as specified in the `[url-handlers]` section for links that have content that doesn't fall into this narrow criteria.  

I think the best way to handle this, if you're willing to consider it, would be to add new keybinds for "open with proxy" and "open with URL-handler". An example would be if I'm over a HTTP link, I could press <kbd>Ctrl + P</kbd> to open it with my proxy and <kbd>Ctrl + U</kbd> to open it with my URL handler.

**Comment by makeworld-the-better-one** [comment]
Thanks for suggesting, this makes sense. I'll add this when I have time, or would accept a PR.

**Comment by nathandaven** [comment]
just curious, what are you using as your proxy? i'd like to set up an http and a gopher proxy to use amfora with

**Comment by makeworld-the-better-one** [comment]
@nathandaven You can view some proxies on the wiki: https://github.com/makeworld-the-better-one/amfora/wiki/Proxying#known-proxies

If you come across any others, let me know and I'll add them!

**Comment by makeworld-the-better-one** [comment]
@lokesh-krishna thinking about this now more that I'm implementing it... isn't just a keybinding for opening with the URL handler needed, <kbd>Ctrl-U</kbd>? Because if you want to use the proxy you can just hit Enter, as your proxy setting overrides any URL handlers.

**Comment by makeworld-the-better-one** [comment]
Ok I added this with just the one keybinding. Let me know if you have any issues @lokesh-krishna.
