### ISSUE TITLE
file:// URI issues

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#147]
- [x] Opening a file:// URI for a directory from the command line blocks files from being opened
- [ ] ~~Scrolling isn't saved~~ It's because the pages aren't cached, whatever

**Comment by makeworld-the-better-one** [comment]
@jedthehumanoid Are you interested in looking into this?

**Comment by makeworld-the-better-one** [comment]
I might disable the `file://` URI feature if these issues seem time-consuming to fix, as I'm pretty close to making a new release otherwise.

**Comment by jedthehumanoid** [comment]
Oh, heads up right away: I'm going to have trouble finding time to do it right now.
I'll try look in to it at some point, but you don't want to plan the release around it. If that means leaving it out, go ahead :)

**Comment by makeworld-the-better-one** [comment]
Thanks for letting me know, no worries. I'll look and see if the fixes are easy, and leave it out in the worst case.

**Comment by makeworld-the-better-one** [comment]
I fixed the main problem in 36455e8, all the rest weren't actually problems or are negligible.
