### ISSUE TITLE
Download path set in config is not respected

### ISSUE THREAD

**Issue by lokesh-krishna** [makeworld-the-better-one/amfora#148]
Tested on the latest release and on master, when downloading on Amfora the file is invariably saved in `~/Downloads`. This is a folder that Amfora creates itself instead of respecting the path set in `~/.config/amfora/config.toml` which is presently set to

```toml
downloads = "/home/loki/downloads/amfora/"
```

**Comment by jedahan** [comment]
This seems a bug, but to help with the immediate issue, I think amfora respects XDG_DOWNLOAD_DIR.

Can you check what XDG_DOWNLOAD_DIR is set to either with `echo $XDG_DOWNLOAD_DIR` or `grep DOWNLOAD ~/.config/user-dirs.dirs`

If neither are set, I think you can `echo XDG_DOWNLOAD_DIR="$HOME/downloads/amfora" >> ~/.config/user-dirs.dirs`

**Comment by makeworld-the-better-one** [comment]
Thanks for reporting. I'll look into it and fix for the next release.

**Comment by makeworld-the-better-one** [comment]
Fixed in 8412b21, I was trying to read config values before the config was actually initialized.
