### ISSUE TITLE
`include` directive for themes in config

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#154]
```toml
[theme]
include = "path/to/file.toml"

# Other keys will override the theme
```

**Comment by crdpa** [comment]
Yes. Include direct to an external .toml file would be nice. Not a network location. That way you could have a folder with lots of themes and just point to the one you want to use.

And it would make contributions for new themes easier.

**Comment by makeworld-the-better-one** [comment]
Sounds good! I'll work on this at some point, or would accept a PR.
