### ISSUE TITLE
Incorrect line wrapping when line has brackets

### ISSUE THREAD

**Issue by sergetymo** [makeworld-the-better-one/amfora#156]
I used to mark inline links with numbers in square brackets, using actual link's sequential number like Amfora itself does. It appears that Amfora incorrectly wraps the kind of lines which contain more than one pair of such link notation, exactly before the word that ends on second pair of brackets.

You can notice such behaviour around words `wraps[2]` and `newsletter[5]` on the screenshot, as well as on the test page [gemini://s.tymo.name/amfora-wrapping-test.gmi](gemini://s.tymo.name/amfora-wrapping-test.gmi).

<img width="1053" alt="Screenshot 2020-12-24 at 01 12 14" src="https://user-images.githubusercontent.com/65758149/103043589-14184080-4586-11eb-8bd4-7b7122f0a530.png">

**Related config entries:**
```toml
[a-general]
left_margin = 0.1
max_width = 100
```

**Details:**
Affected versions: v1.6.0 and v1.7.1
OS: macOS Catalina 10.15.7
Terminals: alacritty v0.5.0, iTerm2 Build 3.4.3, Terminal.app
Fonts and screen sizes: any, changing those doesn't affect the result.

**Comment by makeworld-the-better-one** [comment]
Thanks for the bug report.

This is an upstream issue with the TUI library Amfora uses, cview. See [cview issue 23](https://gitlab.com/tslocum/cview/-/issues/23) for more details. This should be fixed once #107 gets merged, which will update cview and switch to new method for wrapping text.

**Comment by makeworld-the-better-one** [comment]
Whether this will be fixed in #107 is no longer a sure thing unfortunately, as it turns out that "new method" I mentioned cannot be used. See [this upstream issue comment](https://gitlab.com/tslocum/cview/-/issues/27#note_475438483) for more info. If that upstream issue gets fixed then this one can be too, but #107 on its own will not fix this.

**Comment by makeworld-the-better-one** [comment]
#107 has been merged. I'm still waiting for an upstream fix for this unfortunately.

**Comment by makeworld-the-better-one** [comment]
The new place for this issue upstream is [here](https://code.rocketnine.space/tslocum/cview/issues/27). cview moved hosting providers, and the original issue 23 was closed in favor of 27. The bug still exists though.

**Comment by sergetymo** [comment]
Despite upstream issue is not marked as resolved, currently original issue is not reproducible on macOS 12.5 arm64 using
```
❯ amfora -v
Amfora 1.9.2
Commit: 61d864540140f463a183e187e4211c258bd518bf
Built by: homebrew
```

@makeworld-the-better-one , can you please try to visit `gemini://s.tymo.name/amfora-wrapping-test.gmi` on different system and verify if it is fixed, then close this?

**Comment by makeworld-the-better-one** [comment]
Huh, it is fixed. Thanks for spotting this! I'm very curious why this has happened, I'll try and talk to the upstream maintainer. For now I'll close this. Great news!
