### ISSUE TITLE
Allow opening about: pages from cli

### ISSUE THREAD

**Issue by jedahan** [makeworld-the-better-one/amfora#162]
Would be nice for me to start amfora with `amfora about:subscriptions`. Currently, that will segfault on my machine.

**Comment by makeworld-the-better-one** [comment]
It works fine on my machine... Are you using Amfora v1.7.2? And if you are, could you post the output of that segfault?

**Comment by jedahan** [comment]
indeed I was on 1.7.1 and 1.7.2 fixed it
