### ISSUE TITLE
Way to delete bookmarks for pages that don't load

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#163]
Currently the only way to delete a bookmark is to go to the bookmarked page and then use <kbd>Ctrl-D</kbd>. But that makes it impossible to delete a bookmark within Amfora for pages that are gone, or redirect, or if the server is down, etc.

**Comment by Noahnoah55** [comment]
I have two ideas right now. One is to make a separate menu in ```about:bookmarks``` similar to ```about:manage-subscriptions``` full of links to remove bookmarks. The other is to allow ```Ctrl-D``` to work on links without necessarily visiting the page linked to.

I think the first would be the best option, as it would avoid confusion with links to redirects and wouldn't require changing any keybindings for it to work. But I'm also afraid that an ```about:manage-bookmarks``` page might look too similar to the regular ```about:bookmarks``` leading users to accidentally delete bookmarks if they don't notice the difference between both pages.

Maybe I'm overthinking it, but in any case I think I can get a fix for this out.

**Comment by makeworld-the-better-one** [comment]
Thanks for thinking about this! And I'd love to have a PR for it. Personally, I think a managing page would look pretty different, because there would be no custom text, just a list of links that all start with `gemini://`. If you look at `about:manage-subscriptions` you'll see what I mean, it's pretty different.

I think using a shortcut like you mention might be more elegant, but I'd rather match existing behaviour and not muddle the effect of that shortcut.

**Comment by makeworld-the-better-one** [comment]
It's now pretty easy to delete bookmarks that you can't access by editing the `bookmarks.xml` file. I'm not sure how needed this page really is.

**Comment by makeworld-the-better-one** [comment]
Going to take this off the v1.9.0 milestone but leave it open for now. Wondering what any users think about this. I find that the management pages are not a great UX and are quite ugly. Bookmarks that lead to dead links are rare in my experience, and when it does happen, I don't think asking users to edit an XML file is too involved, as this is a terminal application.

If I got a PR implementing this page I would probably reconsider.

**Comment by lee2sman** [comment]
I'm running into this issue (I'm in version 1.8 on Ubuntu) and can't figure out where bookmarks.xml is stored. At least it's not in my ~/.confi/amfora/ directory.

**Comment by makeworld-the-better-one** [comment]
@lee2sman the bookmarks file is in `~/.local/share/amfora` on Linux and macOS by default. It will be `bookmarks.toml` in v1.8.0, and `bookmarks.xml` if you're running off master, or any versions past v1.8.0 (currently none exist).

**Comment by lee2sman** [comment]
Thanks. Maybe this could be added to the wiki

**Comment by makeworld-the-better-one** [comment]
@lee2sman The wiki has a [Bookmarks](https://github.com/makeworld-the-better-one/amfora/wiki/Bookmarks) page now.

**Comment by makeworld-the-better-one** [comment]
Going to close this for now, see [comment](https://github.com/makeworld-the-better-one/amfora/issues/163#issuecomment-834018452). If users really want this feature comment in this thread.
