### ISSUE TITLE
Space isn't used to scroll down

### ISSUE THREAD

**Issue by saper** [makeworld-the-better-one/amfora#164]
I don't know how others feel but I was intuitively pressing space to scroll the page down. Instead, I was getting a - pretty mysterious - "URL/Num./Search:" prompt. 

I wonder how others feel about it?

**Comment by makeworld-the-better-one** [comment]
That prompt is how you enter URLs, or navigate to links, search for things, etc. The next release of Amfora will have support for custom keybindings, it's already in master. So you'll be able to use something other than the spacebar. But the spacebar still won't work for scrolling down a full page, like it does in other terminal programs like `less`. Is that something you'd like? Currently you can use <kbd>d</kbd> and <kbd>u</kbd> to scroll down or up 75% of the page, maybe that's helpful.

**Comment by saper** [comment]
Thank you, I am using master already. Yes, I wanted page down as in w3m or less. I think I don't need customisations, I think they bloat the code too much and it is not needed, so don't worry about it too much. I was just wondering how other users feel about that.

Some random usability notes from a first time user:
* I barely noticed the bar at the bottom after hitting space, also I think that the message is too terse
* It is hard to figure out how to start selecting links unless one presses "?" - Digits are fine once I figured it out. Maybe some kind of tabbing would be great - for your consideration of course.

**Comment by makeworld-the-better-one** [comment]
> it is not needed, so don't worry about it too much

Alright, thanks. I will close the issue then, but feel free to continue to respond to me here.

> I barely noticed the bar at the bottom after hitting space, also I think that the message is too terse

Hmm. I see what you mean, but I'm not sure what to do about it. It's meant to be unobtrusive, and I'm hoping the wiki can inform users that it exists and they should use it.

> scratch that, figured out that tab DOES work :exploding_head:

Indeed :smile:

**Comment by sudobash1** [comment]
> > I barely noticed the bar at the bottom after hitting space, also I think that the message is too terse
> 
> Hmm. I see what you mean, but I'm not sure what to do about it. It's meant to be unobtrusive, and I'm hoping the wiki can inform users that it exists and they should use it.

Perhaps it could change color when it is focused for input?

Personally, when I update and get the custom keybindings, I am going to bind `:` to activate the bottom bar (like my vi instincts want).

**Comment by makeworld-the-better-one** [comment]
The very first sentence of the new tab page explains about the bottom bar and how pressing space will activate it, I think that's enough to tell users that it exists and can be used.

> Personally, when I update and get the custom keybindings

If you're up for it you're welcome to compile from source and try this out now!
