### ISSUE TITLE
flatpak package for Amfora

### ISSUE THREAD

**Issue by ploum** [makeworld-the-better-one/amfora#165]
Would really like to have a flatpak package for Amfora (or a .deb package but I think flatpak would cover more ground).

**Comment by makeworld-the-better-one** [comment]
Good idea! I've never done this before, but would be happy to. I'll look into it when I can.

If anyone else would like to help with this or suggest something, I'd be happy to hear from you. But please don't submit anything to Flathub, as I'd like to be the one in control of the package.

**Comment by makeworld-the-better-one** [comment]
Tips from @/skyjake (@jk@skyjake.fi on mastodon):

> The only thing you need is to write the manifest, basically: https://github.com/flathub/fi.skyjake.Lagrange/blob/master/fi.skyjake.Lagrange.json
>
> You can build/test locally before submitting a PR to Flathub.
>
> Not sure if there's anything specific to console apps, I've only packaged GUI apps so far. Suppose you'll just need to choose the appropriate runtime.

> Almost forgot, you also need to include an AppData doc: https://github.com/skyjake/lagrange/blob/dev/res/fi.skyjake.Lagrange.appdata.xml
>
> That's where the info for the Flathub page comes from.

**Comment by makeworld-the-better-one** [comment]
Required changes

- [ ] Update README with new install instructions
- [ ] Update wiki with new potential places for config files etc
- [ ] Update config file where needed
- [ ] Detect if running in flatpak and use `$XDG_RUNTIME_DIR/app/$FLATPAK_ID` instead of `/tmp` for temporary downloads
- [ ] ...

**Comment by makeworld-the-better-one** [comment]
(Self-note)

Currently having this error:  `lookup proxy.golang.org: Temporary failure in name resolution`

DNS in `flatpak-builder` is failing.

Similar issues:

- https://github.com/flatpak/flatpak/issues/2855
- https://bugzilla.redhat.com/show_bug.cgi?id=1912131

**Comment by makeworld-the-better-one** [comment]
- Get icon to work
- https://github.com/flatpak/flatpak-builder-tools/tree/master/go-get

**Comment by makeworld-the-better-one** [comment]
De-prioritizing this because Amfora doesn't have its own icon, which is needed for Flatpak. Also, as a terminal app written in Go, Flatpak is not a big deal. Just having a way to tell users if they're out of date might be more useful.

Will revisit before making the v1.10.0 release.

**Comment by ploum** [comment]
When I reported this bug, I didn’t understand that flatpak is not really a good idea for command line software. I understand your position and, as the initial reporter, I consider that this could be closed as "WONTFIX". Thanks a lot for your work and investigations.

**Comment by makeworld-the-better-one** [comment]
You're welcome. When I revisit this I will likely close it.
