### ISSUE TITLE
bookmarks: Store the URLs in the bookmarks.toml 

### ISSUE THREAD

**Issue by inet56** [makeworld-the-better-one/amfora#166]
currently amfora store them in a way that is not human readable, but amfora can read them.

I don't know why this mechanism was chosen. If it is necessary to store them in a way they are stored now, at least store the plain text form of URL as comment.

**Comment by Jackymancs4** [comment]
You may want to take a look at https://github.com/makeworld-the-better-one/amfora/issues/68 and/or continue the discussion there, since bookmarks saved as human readable xml strings are an implicit part of that proposal.

**Comment by makeworld-the-better-one** [comment]
Thanks @Jackymancs4, that's what I was going to say as well.

> I don't know why this mechanism was chosen.

The library being used, viper, is a poor choice for *writing* TOML files and has limitations. Periods in the key will mess it up, and the key is case-insensitive, so base32 encoding was used as a hack.

> at least store the plain text form of URL as comments

The library cannot be used to add comments, unfortunately.

Until #68 is resolved I would suggest using the bookmark label (the TOML value) to figure out the URL.
