### ISSUE TITLE
Feature : Read-it later

### ISSUE THREAD

**Issue by ploum** [makeworld-the-better-one/amfora#168]
As I use bookmarks to note posts I should read later, I realise I would appreciate a simple "read it later" features.

The way I see it: 

1) A page with links, similar to a list of bookmarks.
2) When you access a page in that list and scroll until the bottom, the page is removed from the list.
3) When you add a page to that list, there’s no need to add a title. It’s a simple shortcut.

Bonus: new entries in subscribed feeds are automatically added to the "reading list".

What do you think?

**Comment by ploum** [comment]
Technically speaking, that’s indeed the case. But I’m thinking more about a
feature similar to "tour" in AV-98.

**Comment by makeworld-the-better-one** [comment]
`tour` is an interesting feature, I didn't know it had that. But I still don't think it really offers much that's unique as compared to Bookmarks.
