### ISSUE TITLE
Bookmark transference

### ISSUE THREAD

**Issue by johnvile** [makeworld-the-better-one/amfora#174]
Just did a reinstall of operating system. Copied over my setting et-al but the bookmarks in amfora didn't follow :-( 
Tried copying over the /usr/bin/amfora and and ~/.cache/amfora and poked it with a stick. Still didn't work.

Maybe this is a feature request and not really an issue?
Or did I just miss something?
But can't find bookmarks anywhere.

Any ideas?

Thanks

**Comment by makeworld-the-better-one** [comment]
They are in `~/.local/share/amfora`. This is the standard path for application storage on Linux and other OSes that follow the FreeDesktop spec. `~/.cache` is for cached data, and `~/.config` for the configuration. So make sure you copy over `~/.config/amfora` too!
