### ISSUE TITLE
Select two digit numbers using keyboard

### ISSUE THREAD

**Issue by lostleonardo** [makeworld-the-better-one/amfora#175]
I've just discovered Gemini and am really enjoying exploring Geminispace using Amfora. Fantastic work.

When navigating around, I did wonder if it might be possible to add the ability to select two digit links from the keyboard via the use of a modifier key. Something like <Ctrl>+<number><number>. When you release Ctrl, the browser looks for a matching link and, if it finds one, navigates to it. If the browser does not find a matching link or if the user holds down say Ctrl and 'not a number', the browser does nothing.  

I'm not sure if that's a good idea or something anyone else would be interested in or not, but I figured I'd raise it as a possibility.

Thanks for making something that is so useful and fun to use.

**Comment by TheLugal** [comment]
You mean space? Press it and the bar should be activated in the bottom. You may enter links or numbers there.

**Comment by lostleonardo** [comment]
Ahh. My bad. Yeah, that's what I was after. Thanks.

**Comment by makeworld-the-better-one** [comment]
Thanks @TheLugal!

And @lostleonardo, let me know if there's a way I can make this more obvious to users, you're not the first person to bring this up, although you're the first after I made some changes. Using link numbers is mentioned on the front page of the wiki, and the new tab page doesn't explain link numbers, but it mentions using the space bar.

**Comment by makeworld-the-better-one** [comment]
And thanks for the compliments! It means a lot to know that people are enjoying what I've created.
