### ISSUE TITLE
Amfora does not support fully qualified domain names

### ISSUE THREAD

**Issue by sudobash1** [makeworld-the-better-one/amfora#177]
A bit of a nitpick here. I don't know of anybody who types in fully qualified domain names into a URL bar, but I tried on amphora with: `gemini://gemini.circumlunar.space./ ` (Note the ending `.`) I got an error dialog saying:

> Proxy Request Refused: No proxying to other hosts or ports!

I don't know what this error means, but would have expected amphora to take me to the gemini homepage.

For info on fully qualified domain names, I find this page helpful: http://www.dns-sd.org/trailingdotsindomainnames.html

**Comment by makeworld-the-better-one** [comment]
A bit of nitpick here. It's Amfora, not amphora. :smile: 

Thanks for bringing this up! For a moment I was worried, but I think I understand what's going on here. The response you're getting is from the server. It doesn't recognize that domain as its own, and so then it thinks you're trying to use it as a proxy, but that's not allowed according the server config. Basically, this is a bug with [Molly Brown](https://tildegit.org/solderpunk/molly-brown), the server software used on `gemini.circumlunar.space`. I will file a bug report.

Other servers will work fine with this. For example, try accessing `glv.one.` and see that it loads fine.

Amfora could try and "fix" these kinds of domains and remove the dot, but this a rare usecase, and I'd rather stay away from altering user input any more than I have for IDN support.

**Comment by sudobash1** [comment]
Aha. Good sleuthing. I had even tried this on a couple sites, but now I realize that they were all running Molly Brown, so that makes sense.

I definitely agree on not modifying the domain. Amfora is doing the right thing already.

Cheers :beers:
