### ISSUE TITLE
Open images in a user-specified image viewer

### ISSUE THREAD

**Issue by akbarnes** [makeworld-the-better-one/amfora#178]
It would be convenient to be able to open images automatically in something other than the web portal. I'm specifically thinking of tiling-wm-friendly viewers like feh/xsiv

**Comment by makeworld-the-better-one** [comment]
This is actually implemented in master! I just haven't made a release for it yet. If you're comfortable building from source you can try it out. See [this](https://github.com/makeworld-the-better-one/amfora/wiki/Opening-or-streaming-non-text-files) wiki page for details on how it works and how you can use it.
