### ISSUE TITLE
Help screen breaks if you bind | character

### ISSUE THREAD

**Issue by sudobash1** [makeworld-the-better-one/amfora#179]
I took a glance in `help.go` and couldn't help but wonder what would happen if I bound the `|` character to something. Much breakage as it turns out.

With this config:

``` toml
[keybindings]
bind_home = "|"
```

The help screen looks like this:

![image](https://user-images.githubusercontent.com/1923776/107096731-3e356300-67c0-11eb-92a9-442828b9a4be.png)

I will see if I can find a simple fix for this.

**Comment by makeworld-the-better-one** [comment]
Ha, nice one! Thanks for thinking of this.

Any solution you make should target the version of `help.go` on the `cview-update` branch (#107), as that will be merged soon:tm:. In any case, the current task I'm on of Amfora's development is merging that branch, so it's the place to do development. Normally I wouldn't bring this up, but `help.go` has changed significantly between that branch and `master`.

**Comment by sudobash1** [comment]
Aha. Good to now. I had a solution, but it will have to be tweaked.

**Comment by makeworld-the-better-one** [comment]
Closed since #180 and #107 have been merged.
