### ISSUE TITLE
sudo make install error

### ISSUE THREAD

**Issue by webkernel** [makeworld-the-better-one/amfora#193]
Hi,
I followed the instructions to compile amfora on my Trisquel distro. All wentwell unitl sudo make install.

Errors are:
install -m 755 amfora /usr/local/bin/amfora
install -m 644 amfora.desktop /usr/local/share/applications/amfora.desktop
install: cannot create regular file '/usr/local/share/applications/amfora.desktop': No such file or directory
Makefile:24: recipe for target 'install' failed
make: *** [install] Error 1

Can you please help me solve the problem?

Many thanks

**Comment by objectliteral** [comment]
Does `/usr/local/share/applications/` exist on your system? If not, you can create it with `sudo mkdir -p /usr/local/share/applications/` and try again.

**Comment by makeworld-the-better-one** [comment]
I suspect that is the issue as well, thanks @objectliteral.

**Comment by webkernel** [comment]
Thanks for the help.
