### ISSUE TITLE
Bookmark Folders

### ISSUE THREAD

**Issue by SIX10** [makeworld-the-better-one/amfora#194]
Would love these, I have so many bookmarks and they could easily be sorted into recipes or philosophy, blogs, etc.

**Comment by Jackymancs4** [comment]
Hey @SIX10
This is pretty much a dup of #56 and I suggest closing it as such.
You may want to take a look at an underling effort at #68

**Comment by makeworld-the-better-one** [comment]
Yep, this is a duplicate. Glad to hear you'd like it though!

**Comment by SIX10** [comment]
gah im a dummy, thank you tho!
