### ISSUE TITLE
Incorrect handling of URIs with IPv6

### ISSUE THREAD

**Issue by airmack** [makeworld-the-better-one/amfora#195]
The following request will be correctly passed to a server:
amfora [::1]
amfora gemini://[::1]

The following will not be correctly passed to a server:
* amfora [::1]:1965 --> Request will be -->  gemini://::1/  Should be gemini://[::1]/
* amfora gemini://[::1]:1965 --> Request will be -->  gemini://::1/  Should be gemini://[::1]/
* amfora [2a02:8050:b18d:9b00:2d8:61ff:fedd:20ff]:1965 --> Parse "gemini://2a02:8050:b18d:9b00:2d8:61ff:fedd:20ff/": invalid port ":20ff" after host. --> Request will not be propagated to serer

Expected behavior:
Correct handling of URIs and passing according to RFC 3986 (e.g.: https://tools.ietf.org/html/rfc3986#section-3.2.2) , especially with respect to the [ $IPv6 ]:$PORT syntax.

```
   A host identified by an Internet Protocol literal address, version 6
   [RFC3513] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").  This is the only place where
   square bracket characters are allowed in the URI syntax.
```

Thank you very much for work, i really enjoy amfora.

**Comment by makeworld-the-better-one** [comment]
Thanks for bringing this up. I've discovered the issue, it's here:

https://github.com/makeworld-the-better-one/amfora/blob/0e07c4789eaeaaadb77d141a6c13ac85c68ea452/display/util.go#L106-L109

In Go's stdlib, `.Hostname()` will return the IPv6 address without brackets. So if the port is 1965, the port will be removed along with the brackets. I just fixed this by checking whether there's a character that requires brackets, like a colon. This is what `net.JoinHostPort` does as well.

It's fixed now, let me know here if you still experience any problems. Thanks for reporting!
