### ISSUE TITLE
provide advice on or otherwise improve unicode rendering on Windows

### ISSUE THREAD

**Issue by LukeEmmet** [makeworld-the-better-one/amfora#2]
unincode and bullet characters do not display correctly on windows. Initially it seems it could be down to the Windows Terminal, but the same problem is seen in other terminal emulators like the suggested Cmder. Same for favicons such as  makeworld.gq/favicon.txt

Cmder uses ConEmu which claims to support unicode https://conemu.github.io/en/UnicodeSupport.html

Edit: it seems some unicode points are not shown, others are. Strange. The favicon above and the bullets are not though.

![amfora_windows](https://user-images.githubusercontent.com/6898220/85106790-b389fe80-b204-11ea-9e47-e1462a5abdaa.png)
![amfora_cmder](https://user-images.githubusercontent.com/6898220/85106793-b684ef00-b204-11ea-9cfe-bdf07cb94dd0.png)

**Comment by makeworld-the-better-one** [comment]
Thanks for filing this. Can you confirm that unicode bullets display in Windows Terminal or Cmder on their own? Like try pasting them in at the command prompt, or using `echo` to print one.

I'm not doing anything fancy with the unicode, so I'm not sure why this would happen if it's supported. For now you can disable bullets in your config file, which will switch back to asterisks.

**Comment by makeworld-the-better-one** [comment]
@LukeEmmet can you confirm unicode bullets or other unicode characters work outside of Amfora?

**Comment by makeworld-the-better-one** [comment]
v1.2.0 and earlier of Amfora used U+1F784 for a bullet character by mistake. This is the issue with the default Windows Terminal (on LukeEmmet's computer anyway), as it doesn't support that character. However, LukeEmmet has confirmed for me that U+1F784 displays fine in Cmder outside of Amfora, so that doesn't explain the issue there.

**Comment by makeworld-the-better-one** [comment]
LukeEmmet has tested with the latest master, which uses U+2022 for bullets, as it should. The bullets now appear in Windows Terminal and Cmder.
