### ISSUE TITLE
Ability to save `about:` pages

### ISSUE THREAD

**Issue by szczja** [makeworld-the-better-one/amfora#210]
I propose to implement ability to save subscription and bookmark page via CTRL + S. It could be use to publish our feeds and bookmark like CAPCOM. 

It would be interesting if Amfora could be run in command line (from for example crontab) save page, and we could automatically publish that saved pages to our Gemini capsule.

**Comment by makeworld-the-better-one** [comment]
Being able to save them makes sense, I'll add this for the next release. And I agree that command line usage of Amfora makes sense, I'll make a separate issue for that later.
