### ISSUE TITLE
Set keybindings for up/down... movement

### ISSUE THREAD

**Issue by uoee** [makeworld-the-better-one/amfora#211]
I don't notice a way to set my own bindings for scroll up, down (and probably some other basic movements such as left, right too).

Sorry if I'm missing a way to set these, but it seems they must be hardcoded somewhere to arrow keys and hjkl. 

Optionally setting these keys would be helpful for users with alternative keyboard layouts, or users may just have some other preference for how to move about.

**Comment by makeworld-the-better-one** [comment]
Yep, that would be good to add. I will get to this at some point, or would be happy to take a PR.

**Comment by singalhimanshu** [comment]
@makeworld-the-better-one I can work on this one if no one is currently working on it.

**Comment by makeworld-the-better-one** [comment]
@singalhimanshu Sounds good! No one is working on it right now. See #220 for some details on how to add keybindings.
