### ISSUE TITLE
Go to link using numerical keys: why stop at 10?

### ISSUE THREAD

**Issue by wgroeneveld** [makeworld-the-better-one/amfora#215]
Hi there,

I browsed the issues before posting this and couldn't find anything related. The help page states:

> 1 to 0    Go to links 1-10 respectively. 

It happens frequently that I want to go to link 12 or 14 and pressing "1" results in directly going to link 1 instead. Wouldn't it be great if Amfora could record the keypress and wait for a next numerical key within x milisecs? That way, simply pressing "1" and "2" in order would make Amfora go to link 12. This saves a lot of tabbing, especially in articles that denote links inline by something like [12] - which is also used in academic papers. 

Just a suggestion, no idea if it's feasable. Would be great though ;-)
Cheers!
Wouter

**Comment by makeworld-the-better-one** [comment]
Happy to hear you're enjoying Amfora! As noted on the [wiki](https://github.com/makeworld-the-better-one/amfora/wiki#link-navigation), you can just press the spacebar, then the link number, then enter. You probably already know this, but I just wanted to make sure.

Personally I think that's easy enough, but maybe waiting a bit is something to consider.

**Comment by wgroeneveld** [comment]
> Happy to hear you're enjoying Amfora! As noted on the [wiki](https://github.com/makeworld-the-better-one/amfora/wiki#link-navigation), you can just press the spacebar, then the link number, then enter. You probably already know this, but I just wanted to make sure.

Whoops 😊 No, I did not. For me, that's good enough. Thanks!
Maybe it would be a good idea to add that to the help text, directly in proximity to the one I quoted above?

**Comment by makeworld-the-better-one** [comment]
Glad that works for you! It's mentioned in the help text next to each other like this:

```
 Space                Open bar at the bottom - type a URL, link number, search term.                                                                                                         ▒ 
                      You can also type two dots (..) to go up a directory in the URL.                                                                                                       ▒ 
                      Typing new:N will open link number N in a new tab                                                                                                                      ▒ 
                      instead of the current one.                                                                                                                                            ▒ 
                                                                                                                                                                                             ▒ 
 1 to 0               Go to links 1-10 respectively.
