### ISSUE TITLE
Yank current page URI and/or currently highlighted URI

### ISSUE THREAD

**Issue by lostleonardo** [makeworld-the-better-one/amfora#220]
The last time I proposed a UI change, it turned out that Amfora already did it. :-)

With that in mind, is it possible to yank the current URI and put it on the clipboard, without first going into edit mode and mousing over the selection (I would suggest 'yy')? Or, similarly, yank currently highlighted URI ('y')? 

If you like the idea and can point me in the right direction, I could probably have a look at implementing this.

**Comment by makeworld-the-better-one** [comment]
This is not implemented right now. Happy to hear you're interested in adding it yourself.

Adding a new keybinding requires editing `default-config.toml`, `config/keybindings.go`, `config/config.go`, and `display/help.go`.

For yanking the current URI:

- Adding a shortcut that requires timing, like "yy", will be hard if not impossible with the current setup. You should pick a different one.
- To actually activate the keybinding, you'll want to add a case to [this switch](https://github.com/makeworld-the-better-one/amfora/blob/67126ae7855a4b70e723c5f868931fe6a9bfb19d/display/display.go#L297)
- Then in the `case` you can get the `bottomBar` text and put it into the clipboard with a cross-platform clipboard library. Ideally one that doesn't require CGo.

As for yanking the currently highlighted URI (good idea):

- Create a func in `display/tab.go` that returns the currently selected URI, see [these lines](https://github.com/makeworld-the-better-one/amfora/blob/67126ae7855a4b70e723c5f868931fe6a9bfb19d/display/tab.go#L77-L85) for how
- Then add a case to the switch mentioned above that calls that func and uses the clipboard library

**Comment by makeworld-the-better-one** [comment]
Added in #225
