### ISSUE TITLE
Amfora with Termux

### ISSUE THREAD

**Issue by frrobert2** [makeworld-the-better-one/amfora#229]
I am trying to run Amfora with Termux.

I followed the suggested method on the front page. Even after running termux-chroot then running amfora I get the cannot connect error.  Is there another step I need to do?

Thank you.

**Comment by makeworld-the-better-one** [comment]
There shouldn't be, those steps seem to work fine for others. See issues like #120 and #216. Do you want to send the exact commands you ran?

**Comment by frrobert2** [comment]
I am running Termux 0.108
I have downloaded Armfora 1.08  in three different version the 64 bit arm and the 32bit arm6 and 32bit arm7
Proot root was already installed

I first run 
termux-chroot
Then I tried
./amfora_1.8.0_linux_arm64    this errors and will not run because the proot only supports 32bit
I can then run either
./amfora_1.8.0_linux_armv6

or 
./amfora_1.8.0_linux_armv7

Both will start fine but one I try to connect to any site I get the red box that says I cannot connect

I have tried each separately.  With starting termux running  termux-chroot then one of the packages and the results are always the same

Thanks

**Comment by makeworld-the-better-one** [comment]
That's strange. Not sure why that's happening.

@lokesh-krishna @karlh626 any ideas?

**Comment by IzNoGud78** [comment]
I'm unfortunately experiencing another kind of problem on termux.
I tried to follow the required steps but, in my case, in chroot environment amfora doesn't start.

![Amfora issue on Termux with chroot](https://i.imgur.com/E6KVLkU.png)

The only way I have to use amfora on termux is to establish a connection with kiosk via ssh (always in chroot environment).

`ssh kiosk@gemini.circumlunar.space`

than choose amfora among available browsers
This can be a temporary solution, but I hope you can solve this problem

**Comment by makeworld-the-better-one** [comment]
@IzNoGud78 it just stalls after you run the command? That's strange. I'm sorry I'm not really sure about this, it seems there's a few different experiences. I'll ask around and see. Once again tagging @lokesh-krishna @karlh626 to see if they know.

**Comment by IzNoGud78** [comment]
> @IzNoGud78 it just stalls after you run the command? That's strange. I'm sorry I'm not really sure about this, it seems there's a few different experiences. I'll ask around and see. Once again tagging @lokesh-krishna @karlh626 to see if they know.

Thanks for the reply, anyway it seems to be just like that.
Strangely it happens only in chroot environment, if i try to start it outside of chroot it starts normally.

**Comment by karlh626** [comment]
Since the prompt changes after running termux-chroot I would assume that it is entering the chroot environment.

**Comment by IzNoGud78** [comment]
> Since the prompt changes after running termux-chroot I would assume that it is entering the chroot environment.

Obviously yes, I can have confirmation of this also from the fact of receiving a valid output to the command `'ls /usr`

**Comment by IzNoGud78** [comment]
I solved the problem I was experiencing by compiling the source code and using the binary obtained.
Although I must admit that initially, despite having launched the client via the chroot environment, I still ran into the dns lookup issue, after a couple of attempts I was able to use the client without any further problem.

**Comment by Proffy01** [comment]
![IMG-20210509-WA0044.jpg](https://user-images.githubusercontent.com/83601865/117584733-707b9700-b106-11eb-88b7-4d81bffa238c.jpg)

**No such file just erupting my command**
