### ISSUE TITLE
Support common history navigation shortcuts

### ISSUE THREAD

**Issue by LukeEmmet** [makeworld-the-better-one/amfora#23]
It would be nice to support the commonly used keyboard shortcuts for navigating history used in common browsers (firefox, google etc) that we are all trained to use, namely:

ALT+LEFT -> go back
ALT+RIGHT -> go forward

**Comment by makeworld-the-better-one** [comment]
Haha, I've never used those actually. But yep, I'll add them. Note that it's not guaranteed all terminals will support sending those characters though.

Implementation note: Check if [EventKey.Modifiers()](https://godoc.org/github.com/gdamore/tcell#EventKey.Modifiers) is equal to `tcell.ModAlt`, as well as checking for `KeyLeft` and `KeyRight`.

**Comment by makeworld-the-better-one** [comment]
This feature is in the master branch now. It will be in next release. Thanks for trying out Amfora!
