### ISSUE TITLE
Clarification of License for code under /rr

### ISSUE THREAD

**Issue by ecliptik** [makeworld-the-better-one/amfora#230]
Could you clarify what the license is for code under https://github.com/makeworld-the-better-one/amfora/tree/master/rr?

https://github.com/makeworld-the-better-one/amfora/blob/master/rr/README.md states,

```
If you prefer, you can consider the code in this package, and this package only, to be licensed under the MIT license instead.
```

Does this mean code under `/rr` is MIT licensed, and everything else in Amfora is GPL-3.0?

**Comment by makeworld-the-better-one** [comment]
Sorry for being unclear about this. That code can be considered to be dual licensed under MIT and GPL-3.0. For simplicity for Debian packaging as you are doing, it's probably best to consider everything as GPL-3.0. Does that work, legally? Should I clarify something on that README?

**Comment by nileshpatra** [comment]
> Sorry for being unclear about this. That code can be considered to be dual licensed under MIT and GPL-3.0. For simplicity for Debian packaging as you are doing, it's probably best to consider everything as GPL-3.0. Does that work, legally? Should I clarify something on that README?

Nah, that's alright for now. But it'd definitely be nice if you could clearly mention that it is dual licensed - no urgency for now sure.
Thanks for your work in maintaining amfora!

**Comment by makeworld-the-better-one** [comment]
Ok, I tried to clarify in 5a02c2b. Glad that works!
