### ISSUE TITLE
Open files with relative path

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#231]
Right now, Amfora can open files with a command like `amfora file:///absolute/path/to/file`. But it'd be nice if like the `firefox` command, it could just open files and folders with a relative path, like `amfora file.txt`.

The code would first check if the file or folder exists, and then if not interpret it as a URL.

**Comment by singalhimanshu** [comment]
I can work on this if no one else is already on it.

**Comment by makeworld-the-better-one** [comment]
Sounds good! I'll assign it to you. If you end up being unable to work on it for whatever reason, just let me know.
