### ISSUE TITLE
Lists do not get rendered when bullets = false

### ISSUE THREAD

**Issue by regr4** [makeworld-the-better-one/amfora#234]
Hi, whenever my `config.toml` contains `bullets = false`, lists do not show up on screen, but when I have `bullets = true`, then they do show up. I'm using the latest git commit (a4a56a6..) via Homebrew on MacOS with iTerm2. My `config.toml` is almost exactly [`default-config.toml`](https://github.com/makeworld-the-better-one/amfora/blob/master/default-config.toml) except for some color adjustments, and I've confirmed the problem using the default.

To replicate:
- set `bullets = false` in the config
- visit `gemini://gemini.circumlunar.space/`
- there is a missing list after "Gemini is a new internet protocol which:"

I couldn't find another issue about this, my apologies if this is a duplicate.

**Comment by regr4** [comment]
I'm pretty sure the problem is in [`renderer.go`](https://github.com/makeworld-the-better-one/amfora/blob/master/renderer/renderer.go) at line 227: I don't know much about Go, but if I'm reading it correctly, if `bullets` is set to false, it just doesn't render the line. I will try to figure out whether this is the case tomorrow.

**Comment by singalhimanshu** [comment]
> I'm pretty sure the problem is in [`renderer.go`](https://github.com/makeworld-the-better-one/amfora/blob/master/renderer/renderer.go) at line 227

Yeah you are correct that is where the bug is coming from.
Let me know if you are working on this, else I can submit a PR to fix this.

**Comment by regr4** [comment]
I have created a pull request that should fix this issue.

**Comment by makeworld-the-better-one** [comment]
Ouch, sorry about this. You are correct. Will merge #235 ASAP.
