### ISSUE TITLE
Cannot exit help menu after editing the URL or changing the tab

### ISSUE THREAD

**Issue by yaxollum** [makeworld-the-better-one/amfora#241]
When I open the help page using `?` and then I edit the current URL using `e` and press Enter, I am no longer able to exit the help page using `Esc`. 

This issue also seems to also be present when I open the help page and then try to open a new tab using `Ctrl+T`, or move to a different tab using `F1` or `F2`, or reload the page using `R`.

In this situation, the only way (which I know of) to make the help menu go away is to completely exit Amfora.

Is this a bug, or is there something which I'm misunderstanding about the keyboard controls?

**Comment by makeworld-the-better-one** [comment]
This is a bug, thanks for finding it. It will be fixed for the next release.

**Comment by dvejmz** [comment]
I'll be happy to take a stab at this bug. I'd also like to submit it as one of my entries for [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/). If I were to raise a PR to fix this, would you be happy to allow this issue to be entered into the contest by appending the `hacktoberfest-accepted` label to the PR, @makeworld-the-better-one ?

I'd like to have a go at this bug either way but doing it as part of Hacktoberfest would mean I'd have to have the PR ready before the end of the month for it to count.
