### ISSUE TITLE
Cannot use transparrent background

### ISSUE THREAD

**Issue by Andonome** [makeworld-the-better-one/amfora#244]
The lack of transparrent background is messing with my colour schemes. Is it possible to just now have a background colour?

**Comment by m-mcdonagh** [comment]
or possibly a color setting of "None" in the config file, which wouldn't color it in, so if we have a transparent terminal. the terminal remains transparent

**Comment by Andonome** [comment]
`bg = "None"` doesn't work unfortunately.

`Config error: invalid color format for "bg": None`

**Comment by m-mcdonagh** [comment]
I was just making a feature suggestion. 
https://github.com/makeworld-the-better-one/amfora/pull/245/files
I actually implemented it and made a pull request. Hopefully its merged into upstream soon

**Comment by makeworld-the-better-one** [comment]
This issue is already mentioned in #181. But I'll look at that PR.
