### ISSUE TITLE
Not using $XDG_CONFIG_HOME on Windows

### ISSUE THREAD

**Issue by cpkio** [makeworld-the-better-one/amfora#255]
I have `$XDG_CONFIG_HOME` set in Windows (since I use Neovim daily). But Amfora seems to be ignoring it: expected to see Amfora config in my Neovim directory, but `*.toml` are in my `$APPDATA\Roaming\amfora` anyway.

Probably it would be better to provide a separate environment value for config path, so that Amfora could be made portable.

**Comment by makeworld-the-better-one** [comment]
That's correct, Amfora only looks at that variable on *nix systems. I can change that though, I guess there's no harm.

I will get around to doing this, or would accept a PR.

**Comment by makeworld-the-better-one** [comment]
Fixed, this will be in v1.9.0. Technically this could mess up some people's setups if they had this variable set but also had a custom config in the APPDATA folder. Also applies to bookmarks and subscriptions. But I suspect this is very rare, and the files aren't deleted anyway. It will be mentioned in the release notes.
