### ISSUE TITLE
"No route to host" error on amfora client on Void Linux

### ISSUE THREAD

**Issue by gregory3321** [makeworld-the-better-one/amfora#256]
When I want to post something I get "no route to host" error, but post is visible. What's going on?

Disable ufw didn't change anything

**Comment by makeworld-the-better-one** [comment]
> When I want to post something

Are you trying to use a different protocol than Gemini that allows uploading? What is the exact URL you are trying to access? Amfora only supports `gemini://`.

**Comment by gregory3321** [comment]
I try to posting on gemini://matrix.kiwifarms.net

**Comment by gregory3321** [comment]
Now I try to do it, and disable ufw solve problem, but how to solve it with ufw enabled?

**Comment by makeworld-the-better-one** [comment]
It sounds like you're having an issue with UFW, which is not an Amfora issue. You'll have to figure that out elsewhere.
