### ISSUE TITLE
Link numbers cause link titles to wrap beyond the max width setting

### ISSUE THREAD

**Issue by klundry** [makeworld-the-better-one/amfora#280]
When setting the max width setting in the config regular text wraps at the correct width. Link titles on the other hand will extend out past the max width. I believe this is due to the link numbers and associated characters not being accounted for.

**Comment by makeworld-the-better-one** [comment]
This was also an issue for other lines with prefixes, like list lines and quote lines. Thanks for reporting this. The fix is in master and will be in v1.10.0.
