### ISSUE TITLE
Download choice modal loses focus when non-text response is received from CLI URL

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#283]
Run `amfora gemini.thebackupbox.net/radio`. The URL is to a page that returns `audio/mpeg`. The page is loading, then the download choice modal pops up, then the new tab page loads behind it and takes focus, meaning the user can't select a download choice.

**Comment by makeworld-the-better-one** [comment]
Related to #281, if the modal was blocking this wouldn't happen

**Comment by mntn-xyz** [comment]
This also happens if the URL triggers an external handler, for instance "amfora https://example.com" causes the Info dialog to be stuck on screen after the configured browser is opened.

**Comment by makeworld-the-better-one** [comment]
Closed by #284, thanks @awfulcooking!
