### ISSUE TITLE
Request for Pacstall support

### ISSUE THREAD

**Issue by Henryws** [makeworld-the-better-one/amfora#291]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have an ongoing pull request to add [Amfora](https://github.com/pacstall/pacstall-programs/pull/615) to our repository.

We have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation for Amfora for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by makeworld-the-better-one** [comment]
Hello, thanks for reaching out.

The pacstall team maintaining the pacscript themselves would be preferable, thanks. Feel free to ask any questions you have about packaging it in this issue.

> Could you include a section in your documentation showing Pacstall as a valid method of installation for Amfora for Debian/Ubuntu users? We could make a pull request for that if you want.

Pacstall seems like an up and coming project, and while there's nothing wrong with that, I'm not interested in listing every possible package manager, especially alternative ones. Those aware of Pacstall can find Amfora there. If Pacstall gets added to [Repology](https://repology.org/) it will appear on the README anyway.
