### ISSUE TITLE
Preformatted text no longer highlighted

### ISSUE THREAD

**Issue by tgeek77** [makeworld-the-better-one/amfora#292]
In the changelog for 1.7.0., "Preformatted text is now light yellow by default"
However, in the current version, preformatted text is no longer a different color. See attached screenshots. The first is v1.8.0 and the second is v1.9.2.

![v1 8 0_preformatted](https://user-images.githubusercontent.com/10347457/148173822-d4b89dd8-62ff-4ef5-8eee-7621b4325424.png)
![v1 9 2_preformatted](https://user-images.githubusercontent.com/10347457/148173829-afe4c56d-e145-4ec8-96b9-dc9fe85e208f.png)

**Comment by makeworld-the-better-one** [comment]
Yes. Unfortunately this is a side effect of #181. To use the user's terminal colors, I had to stick to the base 16 colors, which didn't leave enough for preformatted text to have its own. I would just add your own entry in the `[theme]` section of your config, like: 
```
preformatted_text = "#ffffaf"
```
