### ISSUE TITLE
Bookmarks Location for Sync

### ISSUE THREAD

**Issue by afrazkhan** [makeworld-the-better-one/amfora#294]
I'm sure I'm being dense, but I've looked all over and can't find where the bookmarks are stored. I'd like to know so I can sync them to my other machines.

**Comment by makeworld-the-better-one** [comment]
Depends on your OS, but all the details can be found on the [Bookmarks wiki page](https://github.com/makeworld-the-better-one/amfora/wiki/Bookmarks). Hope this helps, let me know if you have any other questions!
