### ISSUE TITLE
Subscriptions don't seem to load

### ISSUE THREAD

**Issue by Andonome** [makeworld-the-better-one/amfora#297]
I copied `~/.config/amfora/subscriptions.json` from one computer to anotherr, but those subscriptions aren't showing up on the other computer.

What am I missing?

How do I synchronize subscriptions?

**Comment by makeworld-the-better-one** [comment]
That's strange, that should be the only required file to make things work. Can you tell me more about your setup? What OS and Amfora version is each computer running? You can confirm the version by running `amfora -v` or going to `about:version`. Are their config files the same as well? If not, what are the differences?

Thanks for reporting this.

**Comment by Andonome** [comment]
One runs Void Linux, the other runs Arch.

Both are on Amfora 1.9.2.

I've copied the file over, and checked the md5sum to verify it's the
same file.

If nobody else is getting this, I'll have a look around my configs in
case I did something wrong.

**Comment by makeworld-the-better-one** [comment]
Wait, I think I just figured it out. The subscriptions file is supposed to be stored at `~/.local/share/amfora/subscriptions.json`, not in `~/.config`. Not sure why it would work from that location on your first machine, maybe you had some weird XDG directory setup?

**Comment by Andonome** [comment]
Got it!
Sorry - I did indeed make some  aberations in my setup.

**Comment by makeworld-the-better-one** [comment]
Glad that worked!
