### ISSUE TITLE
Binding Half Page Down

### ISSUE THREAD

**Issue by jonhiggs** [makeworld-the-better-one/amfora#303]
Currently, `bind_pgdn` seems to scoll about 3/4 of a page. I find it difficult to use page up and down because I'm looking to continue reading from the wrong part of the screen. I guess this is learnt behaviour from years of using Vim and Less which both scroll half a page with page up and down (though that might be config on my side).

I would really like some new bindings that will allow me to scroll half a page at a time.

Thanks.

**Comment by makeworld-the-better-one** [comment]
Huh, you're right `less` does scroll only half a page. I think I was copying [Bombadillo](https://bombadillo.colorfield.space/) when I added it, but I assumed that's what `less` did as well. Changed to 50% in 00d90cb.
