### ISSUE TITLE
Add option to force preformatted text to respect max_width

### ISSUE THREAD

**Issue by bzbug** [makeworld-the-better-one/amfora#305]
Problem:

![1043x201_ 10 04 2022 18:19](https://user-images.githubusercontent.com/28236673/162623908-8356178c-b948-4707-a1f4-68ecc06e34fb.png)

The blue is preformatted text that explains how to use blockquotes.

**Comment by makeworld-the-better-one** [comment]
The point of preformatted lines is that they aren't wrapped. From the Gemini spec:

> Graphical clients should use scrolling mechanisms to present preformatted text lines which are longer than the client viewport, in preference to wrapping.

If the line should be wrapped than the author shouldn't use a preformatted block. I don't really get the point of having this option. It's helpful in your case, but that case is very rare. Most of the time it would break things - like code and ASCII art.

**Comment by bzbug** [comment]
And that's why I suggest to add an option. On the second thought, though, maybe not do it as an option but as a command/shortcut. Something like `Toggle [Preformatted text respects max_width]`.

The thing is, my case may be rare but is still a bug that breaks user experience. It breaks the feature the browser itself has - `max_width` setting. If the user has to be afraid that preformatted text won't respect it and the user won't be able to do anything about how the text is presented to him, then the setting does not really work as `max_width` for pages, it works as `max_width_usually_but_not_necessarily_go_resize_your_terminal_when_you_least_expect_it_even_if_you_didn't_ever_want_to_do_it_formatted_text_or_not`.

As far as I understand, Gemini philosophy is that the presentation of the info is controlled by the user. The fact that it is a preformatted text does not mean that it should be displayed as people are used to think of preformatted blocks, even at the expense of usability.

**Comment by makeworld-the-better-one** [comment]
I disagree, it doesn't "break" any feature. The intention of max width was always that it applied to everything but preformatted blocks. I'm not sure what you mean about resizing your terminal, as even when you resize, preformatted blocks don't wrap. This is still the expected behaviour. I don't see the value in changing this.

**Comment by bzbug** [comment]
@makeworld-the-better-one, I meant that preformatted text, when it's significantly wider than other text, requires the user to scroll right/left to see the rest of the preformatted text or to resize the user's terminal in order to see the preformatted text and the other text. In first case the user will scroll right to see the rest of the preformatted text and, by doing that, he will not be able to see the other, not preformatted, text until he scrolls back. It breaks the ability to see the preformatted text in context and read normal text and preformatted text from the start of the line to the end of it without scrolling to and fro. In second case the user decides to resize his terminal if the preformatted text isn't wider than the maximum width of the monitor, for example; in this case resizing the terminal solves the issue of being able to read normal and preformatted text at the same time from the start of the line to the end of the line, but it's very inconvenient.

My point is that it's a ridiculous 'hack' from the user's side to fix presentation of information which should be the browser's feature in the first place. I'm not saying turn off special treatment of preformatted text completely or even by default, because it makes no sense to basically turn off one of the features of Gemini. I'm saying - make it possible for the user to _fix_ presentation of preformatted text in those cases when the owner of the Gemini site decided to make it less flexible by making a long paragraph preformatted and basically screwing all those users who prefer to only view Gemini through a 80-cols-wide terminal windows, or even narrow monitors. And better yet, when the user toggles wrapping of preformatted text, indicate it visually somehow so that the user would remember it's not what the preformatted text block looks like in reality.

**Comment by makeworld-the-better-one** [comment]
I get what you're saying, and it's not such a bad option to have, it just doesn't really make sense to me

> in those cases when the owner of the Gemini site decided to make it less flexible by making a long paragraph preformatted

It would make no sense for an author to do this and would only hinder readers. I think this is a hypothetical that doesn't really happen in the real world. It doesn't make to write code to prevent against this hypothetical.
