### ISSUE TITLE
Is there a way to open files as streams or just download them using a hotkey instead of hard-configuring it in `config.toml` for all cases?

### ISSUE THREAD

**Issue by bzbug** [makeworld-the-better-one/amfora#309]
There is a way to specify which mediatypes should be opened by which applications and whether they should be opened as streams or not in `config.toml`.

But is it possible to not define that behaviour for _all_ files of the same mediatype beforehand and have an ability to choose differently than it is configured when I need it? For example, I usually want to stream video files, no matter their extension, but sometimes I want to download them. The need to do it does not depend on the media type, it depends on the contents of the video itself.

If there is an ability to do that, I suggest stating it clearly in the default `config.toml` file at the very least and then in the official docs when they come out.
If there isn't such an ability, I suggest implementing it as it's more flexible and allows user more control and has an actual use case.

**Comment by mntn-xyz** [comment]
#265 isn't merged yet, but it should be able to do what you are wanting through the use of custom hotkeys for launching applications. You can build the branch yourself if you'd like to try it out. I use it myself and it works.

**Comment by makeworld-the-better-one** [comment]
> For example, I usually want to stream video files, no matter their extension, but sometimes I want to download them.
>
> If there is an ability to do that, I suggest stating it clearly in the default `config.toml` file at the very least and then in the official docs when they come out.

There is such an ability, and it's pretty easy to see. When clicking a video link (after setting `stream = true`) you get the option to Open (which streams), Download, or Cancel.

**Comment by bzbug** [comment]
@makeworld-the-better-one, then I suggest to clarify it somewhere in the default config file and later in full documentation. Because for now it doesn't say anything about the fact that I'll be able to choose whether to stream or to download if I configure something for streaming. It'd be better to say it than to require the user to find out how it works with trial-error approach.
