### ISSUE TITLE
Shortcuts system

### ISSUE THREAD

**Issue by bzbug** [makeworld-the-better-one/amfora#310]
Suggestions:

1. For everything there is that has or can have a shortcut, provide means to re-define the shortcut. Including things like `<Esc>` shortcut at the help page. For me personally it's very inconvenient.
2. If it's possible, split things like help page, modals etc. into different `areas`, so that the same shortcuts could be used with different meaning depending on the context. For instance, so that I could use `q` shortcut for quitting the browser when I'm just looking at a regular page, but so that the same `q` shortcut would quit the help page when I'm there and bring me back to browsing Gemini instead of quitting the browser.
3. Allow shortcuts chains, like `gg` or `;b` or even `Ctrl-T1` (for switching to the 1st tab) and `Ctrl-F1` (for following the first link; the `F1` here is actually not the `F1` btn, it's `Ctrl-F` and then `1` pressed consequetively). Those who don't need that would be able to use shortcuts like they do now, but vim folk will be able to implement more vim-like keybindings and make them more intuitive since pressing a `g` key, for example, would not only mean one action, it might mean many depending on what you press next. Also, for that to work nicely, create a hint shortcuts sheet like in Qutebrowser:

![688x113_ 10 04 2022 19:38](https://user-images.githubusercontent.com/28236673/162627374-adb420bd-4065-435a-a07e-9801b713868b.png)

I pressed `c` here and a small box appeared at the bottom right cornet, near the status bar, and in that box are the shortcuts I can use now after pressing `c` and the actions bound to them.

**Comment by makeworld-the-better-one** [comment]
There are a lot of custom keybindings available, I would accept PRs to add more. But the system you describe is too advanced for me, it sort of becomes high cost low effectiveness - a lot of work but not very useful to me personally. If you made a PR I would consider it, but it's not something I see myself working on. Thanks for you interest in Amfora though.

**Comment by bzbug** [comment]
@makeworld-the-better-one, this is what's written in README.md, in the description of the software:

> **Amfora aims to be the best looking Gemini client with the most features... all in the terminal.** It does not support Gopher or other non-Web protocols - check out Bombadillo for that.
> 
> It also aims to be completely cross platform, with full Windows support. If you're on Windows, I would not recommend using the default terminal software. Use Windows Terminal instead, and make sure it works with UTF-8. Note that some of the application colors might not display correctly on Windows, but all functionality will still work.
> 
> It fully passes Sean Conman's client torture test, as well as the Egsam one.

Because it says so, I assumed that Amfora is an attempt to create a Gemini client that is, well, more feature-rich? And all in terminal.

I mean, not a client that satisfies the needs of most people, but a client that is feature-rich enough to satisfy the needs both of people who aren't very demanding of features and of people who are always left out by mainstream software that implements some nice features not globally and flexibly enough for them to be of much use except in some common cases.

What I suggest now is to re-open the issue so that people would see help is needed and you personally wouldn't have to do this since the described behaviour is not very useful to you as a user and doesn't fall into your use cases. But also mark the issue as something that is desirable, but that's not going to be implemented unless people contribute to it - for the reasons you've explained here.

If this behaviour I described will be banned from implementing even by other contributors, then Amfora is not even close to "a client with the most features", it wouldn't satisfy the needs of the quite large vim gang.

If this behaviour will not be banned from implementing by other contributors, but the issue stays closed, then new contributors may try to implement something close but less flexible because they are unlikely to go and browse all closed issues if they haven't found this one by searching with keywords like "keybindings".

If the issue is not banned from implementing and is open, but not labelled as something strictly for other contributors, many would assume that it's in your Roadmap and you're going to implement it yourself one day.

And I suggest doing the same thing for #311, which is even more important imo since it allows to not just re-define shortcuts for already existing functions, but also to create new ones and automate the browser to the user's needs.

**Comment by makeworld-the-better-one** [comment]
Ultimately the goal stated on the README is secondary to my desires, and also what I am able to maintain. A large complex feature like this will be difficult to maintain, and is hard to justify to myself personally because I don't even want it. If a PR is made I will consider it, but in general I think it's fine for this issue to stay closed. The feature itself is not banned.
