### ISSUE TITLE
Command mode

### ISSUE THREAD

**Issue by bzbug** [makeworld-the-better-one/amfora#311]
Suggestions:

1. For everything there is that can be considered a browser action user might want to execute (from setting the settings and quiting the browser to scrolling pages by perc or lines and navigating the links) should be a real command in the command mode (when you press the default `<Space>` hotkey and can now type stuff into the bottom bar).
2. Create completions panel for commands like in Qutebrowser. Make the completions displayed context-sensitive (depending on the arguments you've already entered). Make it also a standard to be able to display the current value of any setting (even if it's not changed in the `config.toml` and currently has the default value). Examples of Qutebrowser's completion panel:
   1. Global commands:
![975x533_ 10 04 2022 19:48](https://user-images.githubusercontent.com/28236673/162627835-0bc63c21-62e4-4725-bc38-c8075ecf39eb.png)
   2. Setting options (context-sensitive completions, the `:set` command is used for setting options and the completions are guessed based on that, it even says in the title of the panel that the current context is for setting options):
![976x537_ 10 04 2022 19:52](https://user-images.githubusercontent.com/28236673/162628009-d59b2821-293f-4c9f-b37b-8944c5e95363.png)
3. Ability to create 'new' commands by aliasing any other native commands together in a chain and then to define new shortcuts for those user-defined aliases, like in Qutebrowser. This will allow any user to tweak and extend and automate a lot of the browser's behaviour to their tastes.

**Comment by makeworld-the-better-one** [comment]
Similar to #310, this is a lot of work for a feature I'm not super interested in. It's cool to have those browser commands, but personally I'm happy with the bar just being a search/URL bar, and triggering commands using short cuts.
