### ISSUE TITLE
Open/Download/Cancel buttons inaccessible

### ISSUE THREAD

**Issue by nervuri** [makeworld-the-better-one/amfora#317]
Example: I run `amfora gemini://skyjake.fi/media/dash.png` in the terminal.  The "Open/Download/Cancel" prompt appears, but I can't select any of the 3 options.  Instead, keyboard commands act on the "about:newtab" page that is open in the background.

If I first open amfora, then navigate to the same image, the dialog works as intended.

I'm using:

```
Amfora 1.9.2
Commit: 61d864540140f463a183e187e4211c258bd518bf
Built by: goreleaser
```

**Comment by tarial** [comment]
Similarly, if you open an external link in a new tab using <Ctrl> + <T> the popup informing you the page is opened in a web browser does not get the focus and can't be closed.

I'm also using:
```
Amfora 1.9.2
Commit: 61d864540140f463a183e187e4211c258bd518bf
Built by: goreleaser
```

**Comment by makeworld-the-better-one** [comment]
Thanks for filing this bug report, sorry I've taken so long to get back to you. This does not occur with the unreleased version of Amfora in the master branch. For example I just tested with this version and didn't experience the error:

```
Amfora v1.9.2-32-g3917402
Commit: 3917402e2d44b6a302bf4a4d39570896a989d29c
Built by: Makefile
```

**Comment by tarial** [comment]
Can confirm the issues reported above do not occur with the latest commit ([1d257f9](https://github.com/makeworld-the-better-one/amfora/commit/1d257f908a5e8849785ab8f2756b9f59cb35b0f4)).
