### ISSUE TITLE
fatal error: sync: Unlock of unlocked RWMutex

### ISSUE THREAD

**Issue by gregory3321** [makeworld-the-better-one/amfora#318]
Someone report this error and I don't find it beacause I wrong type it in search bar, sorry ;(

I will be more carefull in future, sorry again.

**Comment by gregory3321** [comment]
Amfora 1.9.2 Commit: 61d864540140f463a183e187e4211c258bd518bf Built by: Alpine_Linux

**Comment by makeworld-the-better-one** [comment]
No worries.
