### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by bouncepaw** [makeworld-the-better-one/amfora#46]
It'd be good to have an option to change colors of the browser. The default forced white-on-black colorscheme is too heavy for my eyes. I couldn't find any way to change it. Even if I turn off colors in config, it is still white-on-black.

Perhaps an option to fall back to shell colorscheme would be great. It would work perfect for everyone.

**Comment by makeworld-the-better-one** [comment]
Thanks for the request, I will look into this.

**Comment by makeworld-the-better-one** [comment]
Self note: Add a `[theme]` section to the config, where [xterm colors](https://jonasjacek.github.io/colors/) for all the theme elements (bg, links, headings, etc) can be set by color number, 0-255. Look into if there's a way to support hex codes for all things or not.

**Comment by makeworld-the-better-one** [comment]
New idea: Support W3C color names and hex codes using `tcell.GetColor`.

**Comment by makeworld-the-better-one** [comment]
This was added in 56a5689, and will be in v1.4.0. Thanks for the suggestion! I didn't find an easy way to fallback to the user's terminal color scheme, but now you can change Amfora's colors all you want.

**Comment by bouncepaw** [comment]
Neat. Thanks!
