### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/amfora#63]
Hello @makeworld-the-better-one 
I recently jumped on the gemini train, and after some trials and tests I settled on using your awesome client!
Thank you very much for this.

I'm maintaing a small personal tap (repository) for the [Homebrew Package manager](https://brew.sh) and I recently added a formula (package) for `amfora`.

Homebrew is very popular on Mac, but works on both Linux (Linuxbrew) and Windows (using WSL). I tested the program on all three platforms.

Now, for anybody else using homebrew, amfora can be installed with
```
$ brew tap jackymancs4/tap
$ brew install amfora
```

or, as a one-liner:

```
$ brew install jackymancs4/tap/amfora
```

Since I'm planning to use it for personal purpose, I will take care of keeping it updated, so that a simple

```
$ brew upgrade amfora
```

will keep the installation fresh.
Just wanted to let you know about it.

**Comment by makeworld-the-better-one** [comment]
Awesome, thanks! Happy to hear you like Amfora. I will add this to the README. And please let me know if this ever makes it into the main homebrew repository.

**Comment by Jackymancs4** [comment]
Hey @makeworld-the-better-one 
Today I updated the amfora homebrew formula to 1.5.0
I see now that you changed the recommended way of installing Amfora to use (g)make.
Are there any known issues with the current method or can I wait 1.6.0 before switching? Current build system (go build) on 922e7981a92cb7bf0d7b3baf1694d0fffe90d448 worked flawlessly.

**Comment by makeworld-the-better-one** [comment]
Also there's no point in installing the `amfora.desktop` file by the way, as it's a Linux thing.

**Comment by Jackymancs4** [comment]
I'm aware of this. Homebrew works also in Linux (I use it on my Ubuntu installation) so the `.desktop` is usefully installed there, while on macOS it make no harm. Multiple other formulas install theirs on both platforms.

**Comment by Jackymancs4** [comment]
After a couple more tests, I will deprecate my formula in favour of yours (https://github.com/makeworld-the-better-one/homebrew-tap/blob/master/Formula/amfora.rb) so you may want to update the README which links to mine.

**Comment by makeworld-the-better-one** [comment]
@Jackymancs4 Please don't do that yet, as mine currently does not work, it's still in progress. I will update the README and you in this thread once it's ready.

**Comment by Jackymancs4** [comment]
> as mine currently does not work

Yes, I noticed that, hence my tests about it where still ongoing 👍

**Comment by makeworld-the-better-one** [comment]
It works now, I will be updating the README. Thanks for maintaining the tap in the meantime.

**Comment by Jackymancs4** [comment]
Can I give you some feedback about it on the appropriate repo?

**Comment by makeworld-the-better-one** [comment]
For sure! I'm new to creating homebrew formulas. One thing I'm wondering, if you don't mind, is how to only run a command if the version is not HEAD. Specifically I want to disable this line when a user installs from HEAD:

```ruby
system "curl", "-sSL", "https://github.com/makeworld-the-better-one/amfora/raw/b2b8e30/Makefile", "-o", "Makefile"
```
