### ISSUE TITLE
Custom new tab page

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/amfora#67]
Hello @makeworld-the-better-one 
I see here:
https://github.com/makeworld-the-better-one/amfora/blob/master/display/newtab.go

That you hard coded the content of the new tab page. After a while I almost learned it by memory.

It would be cool if instead the page was loaded from e.g. `$HOME/.config/amfora/newtab.gmi` (or relative XDG setting). This would allow for higher level of customization, both static (a short list of uber-favourite list of sites), and dynamic (like a cronjob that pipe `fortune` messages into it).

p.s
The title is not very descriptive. Feel free to rename it.

**Comment by makeworld-the-better-one** [comment]
This would be a cool feature, thanks. It'd be nice if the page could be cached on startup, but would that break your dynamic idea?

**Comment by Jackymancs4** [comment]
> but would that break your dynamic idea?

No, not really. It feels like a potentially different newtab page per session (instead of per tab open) is more than enough for cool ideas to emerge.

Still, as potential fix, you could allow the reload function (`ctrl-r`) to also affect the newtab page.

**Comment by makeworld-the-better-one** [comment]
Added by #83, merged into master at 9d7c7370e087cce1db3f9a24dfd39d5ddbc3d307. It will be in v1.5.0.
