### ISSUE TITLE
Emoji favicons on bookmarks page

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#69]
Only if `emoji_favicons` is enabled.

```
# Bookmarks

[1] 🌻 Astrobotany

...etc...
```

**Comment by alexwennerberg** [comment]
What do you think the best way to do this is? Set the emoji on write, or pull it when bookmarks page is loaded (cached)?

**Comment by makeworld-the-better-one** [comment]
Added in #90.
