### ISSUE TITLE
Switching tab is impossible with AZERTY keyboard

### ISSUE THREAD

**Issue by Eluminae** [makeworld-the-better-one/amfora#70]
Shift-Number is in fact Number with this kind of keyboard. Pressing Shift-Number will just open link.

Is there a way to configure binds or is there alternative to switch tabs ?

**Comment by makeworld-the-better-one** [comment]
Hello, thank you for your interest in Amfora. Please note that switching tabs will still be possible in v1.5.0, as <kbd>F1</kbd> and <kbd>F2<kbd> have been added for left and right tab switching in 5cb629f.

I will look into a general keybindings solution in the future.

**Comment by Eluminae** [comment]
Really nice. Thanks a lot for the work. Amfora rocks :stuck_out_tongue:

**Comment by makeworld-the-better-one** [comment]
Would you be okay with closing this issue, now that there's a way to switch tabs?

**Comment by Eluminae** [comment]
Yeah ofc !
