### ISSUE TITLE
Accept spaces in paths in http config setting

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/amfora#77]
Hello @makeworld-the-better-one 
I'm using amfora 1.4 for linux on a Windows machine using WSL.

Obviously, in this setup there is no detectable GUI nor browser, so when trying to open an http link it fails.

To overcome this, I manually set the `http` setting value from `default` to `/mnt/c/Program Files/Mozilla Firefox/firefox.exe`.

Amfora then prompt me with:
`Error executing custom browser command: fork/exec /mnt/c/Program: no such file or directory`

It appears that the spaces in the path are not properly escaped. 

So I chanced the setting to `/mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe` but again amfora prompt the error `Error executing custom browser command: fork/exec /mnt/c/ProgramFiles/MozillaFirefox/firefox.exe: no such file or directory.` which shows that the spaces have been removed.

**Comment by Jackymancs4** [comment]
After a minor investigation I found that the issue originates here:
https://github.com/makeworld-the-better-one/amfora/blob/5e417b040bfdfb366fcdea0c95da496871db8833/display/private.go#L156

I see why you used `strings.Fields`, but a path with spaces is still a valid path. 
Given the complexity of this kind of things, maybe a dedicated library like https://github.com/mattn/go-shellwords (from https://groups.google.com/g/golang-nuts/c/pNwqLyfl2co?pli=1)

**Comment by makeworld-the-better-one** [comment]
Thanks for finding this, I see the problem. I will look into using go-shellwords, thanks for finding that library.

Can I ask why you're using Amfora through WSL instead of just on Windows directly?

**Comment by Jackymancs4** [comment]
> Can I ask why you're using Amfora through WSL instead of just on Windows directly?

No particular reason, I'm more of a Linux person, but have to use Windows for work (and games) so I try to replicate my terminal setup as much as possible on both platforms.

**Comment by makeworld-the-better-one** [comment]
I was thinking about accepting an array of strings as well as just a single string for this setting, and all other shell command based settings. So if you want something other than the naive space splitting, you can do the splitting yourself with an array.

For your example:
```toml
http = ["/mnt/c/Program Files/Mozilla Firefox/firefox.exe"]
```

A more complex example, that fails with the current code:
```toml
http = ["some-command", "--flag", "/path/with spaces/here.txt"]
```

**Comment by Jackymancs4** [comment]
The solution as you described sounds perfect.
