### ISSUE TITLE
Per-scheme proxy server

### ISSUE THREAD

**Issue by makeworld-the-better-one** [makeworld-the-better-one/amfora#80]
Right now there's just a `a-general.proxy` setting for Gemini proxies, but @LukeEmmet mentioned on IRC that it'd be nice to be able to set a different proxy server for each URL scheme.

Apparently the diohsc client does this: "Facilities to invoke external commands and use per-scheme proxies."

This should override any command settings for the scheme of the link, if they exist.

- [x] Move `a-general.proxy` to a `[proxies]` section that works like `[url-handlers]`

**Comment by LukeEmmet** [comment]
Also [AV-98](https://tildegit.org/solderpunk/AV-98/src/branch/master/av98.py) has a gopher proxy
