### ISSUE TITLE
Prompt before quitting

### ISSUE THREAD

**Issue by sotpapathe** [makeworld-the-better-one/amfora#82]
Showing a yes/no prompt would be useful in preventing accidental quits. An additional keybinding (`Q` maybe?) could be added to quit without a prompt.

I tried implementing this [here](https://github.com/sotpapathe/amfora/commit/1345290b482d05de3a9cd9fc11d34b161492207d) but the program freezes when pressing `q`. Info/Error modals seem to work but the YesNo modal does not appear at all. What should I look into to fix this?

**Comment by makeworld-the-better-one** [comment]
`YesNo` needs to run in a goroutine, I should document that. So the code would look like this:

```go
go func() {
	if YesNo("Really quit? ") {
		Stop()
	}
}()
return nil
```
There is other display code that will prevent the user from doing other things while the modal is open.

As for what you're actually trying to achieve, I don't feel like this prompt is really necessary, I like being able to close Amfora with a single key. All that would be potentially lost is the tabs you have open.

**Comment by sotpapathe** [comment]
Thanks for the tip, that worked!

| I don't feel like this prompt is really necessary

I'll keep it as a private patch for now then. I can submit it when custom keybindings are implemented.
