### ISSUE TITLE
make install fail on MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/amfora#85]
`make` works, but `make install` consistently fails.

With gmake 
```
$ gmake install
Installing Amfora to /usr/local/bin
install: root: Invalid argument
gmake: *** [Makefile:27: install] Error 67
```

With make
```
$ make install
Installing Amfora to /usr/local/bin
install: root: Invalid argument
make: *** [install] Error 67
```

After a very brief google search I found this https://github.com/osmcode/libosmium/issues/18 and the relative fix https://gist.github.com/tmcw/7223147 

It appears to be related to the admin user group which is different in MacOS/BDS and Linux systems. I may be wrong though.

**Comment by Jackymancs4** [comment]
I'm no expert, but I also do not understand why here https://github.com/makeworld-the-better-one/amfora/blob/84efeb5d9cbd46d2bb919b37c70cb4978a0c20b4/Makefile#L15 the file must be owned by root.

IIRC `/usr/local/bin` should be writable by pretty much any user.

**Comment by makeworld-the-better-one** [comment]
Thanks for finding this bug. I will change the group to `0`, as libsodium did [here](https://github.com/osmcode/libosmium/commit/6e92f6cc42018cc5d98e249fd732ee29a4db1809).

`/usr/local/bin` is not writable by regular users on most systems actually, I just tested this on Arch Linux and Debian. Having root own the file is just cleaner if you need root access to copy/move the file anyway.

**Comment by makeworld-the-better-one** [comment]
You shouldn't be using `make install` for your Homebrew package by the way, because it install to `/usr/local/bin`, not the proper Homebrew directory.

**Comment by Jackymancs4** [comment]
> You shouldn't be using make install for your Homebrew package

I wasn't planning to, just testing, but there is quite a few ways I could have handled this in the formula, like overriding the prefix variable (which is a pretty common technique).

**Comment by makeworld-the-better-one** [comment]
Yeah okay. The Makefile has been updated btw, check it out again.
