### ISSUE TITLE
Show indicator of scroll level

### ISSUE THREAD

**Issue by Jackymancs4** [makeworld-the-better-one/amfora#89]
Hello @makeworld-the-better-one 

I found myself reading a very long gemini post recently (for reference: gemini://l-3.space/split-keys.gmi ) and it came up in my mind that it would be nice to now how long until I reach the end.

As a possible idea, splitting the bottom status bar in two, where on the left there is the bar as there is now, and aligned on the right there is somenthing like `number_bottom_line:number_of_lines_in_document` or some form of percentage.

Ideally some form of scroll bar (vertical) or reading progress bar (horizontal).

**Comment by makeworld-the-better-one** [comment]
This is a good idea, thanks. The underlying TUI library Amfora uses, [cview](https://gitlab.com/tslocum/cview/) supports scrollbars for some things, but not just text views, like pages are. I've opened up [issue 34](https://gitlab.com/tslocum/cview/-/issues/34) to see if that could be supported.

Having some stats in the bottom right is a good solution, I like it a lot, for all kinds of things potentially (meta string, for example). Unfortunately, the current object for the bottom bar is an `InputField`, which will make adding arbitrary right-aligned text not straight-forward. Definitely possible though, so I will look into it at some point.

**Comment by makeworld-the-better-one** [comment]
> This is a good idea, thanks. The underlying TUI library Amfora uses, [cview](https://gitlab.com/tslocum/cview/) supports scrollbars for some things, but not just text views, like pages are. I've opened up [issue 34](https://gitlab.com/tslocum/cview/-/issues/34) to see if that could be supported.

Issue 34 has been closed, scrollbars for text views are now supported in cview commit [441992fd](https://gitlab.com/tslocum/cview/-/commit/441992fd77e8d4e8d18c0f48413f158523c3a361).

I plan on updating the cview dependency to support to this feature, and adding a new config option to turn it on and off. I'm thinking of leaving it on by default, but open to hearing opinions on that.

**Comment by bouncepaw** [comment]
I like `vim`'s approach to this. It shows `Top` on top of document, `Bot` on bottom and percentage in other cases. It's quite handy and intuitive (if you rename `Bot` to `Btm` or `100%`).

**Comment by makeworld-the-better-one** [comment]
This will be fixed in #107.

**Comment by makeworld-the-better-one** [comment]
@Jackymancs4 You mentioned an approach using line numbers originally, and @bouncepaw you mentioned percentages. While the scroll bar method mentioned above is still planned, I will also be adding support for these other methods as part of an info bar. See #142 and feel free to comment there.

cc @pixdrift
