### ISSUE TITLE
Parse XDG config file for user dirs

### ISSUE THREAD

**Issue by pniedzwiedzinski** [makeworld-the-better-one/amfora#97]
[XDG user dirs](https://wiki.archlinux.org/index.php/XDG_user_directories) specify the user's download directory, so if this is set amfora should use these directories for saving downloaded documents.

**Comment by makeworld-the-better-one** [comment]
Thanks for linking this. It looks like Amfora should be retrieving *all* its XDG variables from that local config file, and not checking actual env vars at all. I think I can use the [xdg/userdirs](https://godoc.org/github.com/rkoesters/xdg/userdirs) package to do this.
